version: "3.7"

services:
  api:
    build: ./api
    volumes:
      - ./api:/api
    command: ["uvicorn", "api.main:api", "--reload", "--host", "0.0.0.0"]
    env_file:
      - ./api/.env
    #network_mode: "host"
    ports:
      - 8001:8000

  mongo:
    image: mongo:4.4-bionic
    restart: unless-stopped
    #network_mode: "host"
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: twitscrapper
      MONGO_INITDB_ROOT_PASSWORD: twitscrapper
      MONGO_INITDB_DATABASE: twitscrapper
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.54
    restart: unless-stopped
    #network_mode: "host"
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: twitscrapper
      ME_CONFIG_MONGODB_ADMINPASSWORD: twitscrapper

volumes:
  mongo-data:
